branch-defaults:
  master:
    environment: landmark-deciderer-dev
    group_suffix: null
deploy:
  artifact: target/build.zip
environment-defaults:
  landmark-deciderer-dev:
    branch: master
    repository: null
global:
  application_name: landmark-deciderer
  default_ec2_keyname: torchbearer
  default_platform: 64bit Amazon Linux 2017.03 v2.6.0 running Docker 1.12.6
  default_region: us-west-2
  profile: torchbearer
  sc: git
